export const DELETE_PREV_LINE_SEQUENCE = '\x15'
export const DELETE_PREV_WORD_SEQUENCE = '\x17'
export const DELETE_NEXT_WORD_SEQUENCE = '\x1bd'
export const UNIX_WORD_RUBOUT_SEQUENCE = '\x1b\x7f'
export const DELETE_NEXT_CHAR_SEQUENCE = '\x1b[3~'
