import { z } from 'zod'

const identifier = z.string().min(1).max(120)
const filePath = z.string().max(4096)
const repositoryPath = z.string().min(1).max(4096)
const repositoryFilePath = z.string().min(1).max(4096).refine((value) => !value.startsWith('/') && !value.split('/').includes('..'), 'Invalid file path')

export const hostParamsSchema = z.object({ hostId: identifier })
export const hostIdParamsSchema = z.object({ id: identifier })
export const fileContentBodySchema = z.object({ root: identifier, path: filePath, content: z.string().max(1024 * 1024), modifiedAt: z.string().datetime().optional() })
export const fileEntryBodySchema = z.object({ root: identifier, path: filePath, name: z.string().min(1).max(255) })
export const fileTransferBodySchema = z.object({ root: identifier, path: filePath, targetRoot: identifier, targetPath: filePath })
export const fileTrashBodySchema = z.object({ root: identifier, path: filePath })
export const fileRestoreBodySchema = z.object({ trashId: identifier })
export const fileRemoveQuerySchema = z.object({ root: identifier, path: filePath })
export const paneIdBodySchema = z.object({ paneId: z.string().min(3).max(256) })
export const paneSplitBodySchema = paneIdBodySchema.extend({ direction: z.enum(['horizontal', 'vertical']) })
export const paneResizeBodySchema = paneIdBodySchema.extend({ cols: z.number().finite().optional(), rows: z.number().finite().optional() })
export const sessionCreateBodySchema = z.object({ name: z.string().min(1).max(64), layout: z.any().optional() })
export const sessionRenameBodySchema = z.object({ sessionId: z.string().min(1).max(256), name: z.string().min(1).max(64) })
export const gitFilesBodySchema = z.object({ path: repositoryPath, filePaths: z.array(repositoryFilePath).min(1).max(1000) })
export const gitCommitBodySchema = z.object({ path: repositoryPath, message: z.string().min(1).max(65536), amend: z.boolean().optional() })
export const gitResolveBodySchema = z.object({ path: repositoryPath, filePath: repositoryFilePath, resolution: z.enum(['ours', 'theirs', 'mark']) })
export const gitOperationBodySchema = z.object({ path: repositoryPath, operation: z.enum(['merge', 'rebase']), action: z.enum(['continue', 'abort']) })
export const remoteHostBodySchema = z.object({ id: identifier, name: z.string().max(120).optional(), address: z.string().min(1).max(255), user: z.string().min(1).max(120), port: z.number().int().min(1).max(65535).optional(), password: z.string().max(1024).optional(), passwordEnv: z.string().max(120).optional() })
export const pluginLinkBodySchema = z.object({ path: z.string().min(1).max(4096) })
export const pluginInstallBodySchema = z.object({ source: z.string().min(1).max(512), resolvedCommit: z.string().min(1).max(128), ref: z.string().max(256).optional() })
export const streamMessageSchema = z.object({ type: z.string().min(1).max(64) }).passthrough()
export const streamAttachMessageSchema = z.object({ type: z.literal('attach'), hostId: identifier.optional(), sessionName: z.string().min(1).max(256), exclusive: z.boolean().optional(), cols: z.number().finite().optional(), rows: z.number().finite().optional() })
export const streamInputMessageSchema = z.object({ type: z.literal('input'), data: z.string().max(1024 * 1024) })
export const streamResizeMessageSchema = z.object({ type: z.literal('resize'), cols: z.number().finite(), rows: z.number().finite() })
export const streamRegisterMessageSchema = z.object({ type: z.literal('register'), host: z.object({ id: identifier, name: z.string().min(1).max(120), address: z.string().min(1).max(255) }) })
